apiVersion: v1
kind: ConfigMap
metadata:
    name: rider-service-config
    namespace: rideshare-app
data:
    NODE_ENV: production
    PORT: "3001"
    JWT_EXPIRES_IN: "7d"
    FRONTEND_URL: "https://light.rideshare.teleioslabs.net"
    EMAIL_SERVICE_URL: "http://email-service.rideshare-app.svc.cluster.local:3002"
    RIDER_SERVICE_URL: "http://rider-service.rideshare-app.svc.cluster.local:3001"
    TRIP_SERVICE_URL: "http://trip-service.rideshare-app.svc.cluster.local:3005"
    REDIS_TLS: "true"