
apiVersion: v1
kind: Service
metadata:
    name: driver-service
    namespace: rideshare-app
    labels:
      app: driver-service
spec:
    selector:
      app: driver-service
    ports:
      - port: 3003
        targetPort: 3003
        protocol: TCP