apiVersion: v1
kind: ConfigMap
metadata:
  name: matching-service-config
  namespace: rideshare-app

data:
  NODE_ENV: "production"
  PORT: "3004"
  REDIS_TLS: "false"
  TRIP_SERVICE_URL: "http://trip-service.rideshare-app.svc.cluster.local:3005/api/v1/trips"