apiVersion: v1
kind: Service
metadata:
  name: matching-service
  namespace: rideshare-app
  labels:
    app: matching-service

spec:
  selector:
    app: matching-service

  ports:
    - port: 3004
      targetPort: 3004
      protocol: TCP

  type: ClusterIP